import {StyleSheet} from 'react-native';
import COLOR from '../../../constants/COLOR';

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLOR.BLUE,
  },
  contaier: {
    backgroundColor: COLOR.BLUE,
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    marginLeft: 10,
    marginTop: 8,
  },
  entryWrapper: {width: '100%'},
  main: {
    backgroundColor: COLOR.BLUE,
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',

    justifyContent: 'flex-start',
  },
  mainItem: {
    minHeight: 165,
    maxHeight: 165,
    minWidth: 168,
    borderRadius: 20,
    backgroundColor: COLOR.WHITE,
    margin: 5,

    marginTop: 5,
  },
  singleMainItem: {
    minHeight: 165,
    maxHeight: 165,
    minWidth: 168,
    borderRadius: 20,
    backgroundColor: COLOR.PINK,
    margin: 5,
    marginTop: 5,
  },
  topItem: {
    height: '33%',
    justifyContent: 'center',
    width: '100%',
    alignItems: 'center',
    borderTopLeftRadius: 20,
    borderWidth: 1,
    borderTopRightRadius: 20,
    borderColor: COLOR.WHITE,
    borderBottomColor: COLOR.BLUE,
  },

  midelItem: {
    height: '33%',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  midelItemSelected: {
    height: '33%',
    backgroundColor: COLOR.PINK,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomItem: {
    height: '34%',
    justifyContent: 'center',
    width: '100%',
    alignItems: 'center',
    borderBottomLeftRadius: 20,
    borderWidth: 1,
    borderBottomRightRadius: 20,
    borderTopColor: COLOR.BLUE,
    borderColor: COLOR.WHITE,
  },
  bottomItemSelected: {
    height: '34%',
    justifyContent: 'center',
    width: '100%',
    alignItems: 'center',
    borderBottomLeftRadius: 20,
    borderWidth: 1,
    borderBottomRightRadius: 20,
    borderTopColor: COLOR.BLUE,
    borderColor: COLOR.PINK,
    backgroundColor: COLOR.PINK,
  },
  titleStyle: {margin: 10, fontSize: 18, opacity: 0.4, color: COLOR.BLACK},
  titleStyleSingle: {
    margin: 10,
    fontSize: 18,
    color: COLOR.WHITE,
  },

  textColor: {color: COLOR.WHITE, fontSize: 18},
  textColorSelected: {color: COLOR.TAB_ICON, fontSize: 18},
  confirmButton: {position: 'absolute', bottom: -18, left: 140, zIndex: 2},
  confirmImage: {
    width: 50,
    height: 50,
  },
  resultTitle: {
    backgroundColor: COLOR.TAB_ICON,
    width: '100%',
    height: '100%',
    borderRadius: 20,
  },
  resultTitleText: {margin: 10, fontSize: 18, color: COLOR.WHITE},
  resultText: {
    margin: 5,
    marginHorizontal: 10,
    fontSize: 16,
    color: COLOR.WHITE,
  },
  mainNoteWrapper: {
    height: 300,
    width: '100%',
    backgroundColor: COLOR.BLUE,
  },
  noteWrapper: {
    width: '90%',
    margin: 20,
    marginBottom: 0,
    borderWidth: 1,
    borderTopColor: COLOR.TOPLINE,
    borderColor: COLOR.BLUE,
  },
  textNote: {
    marginTop: 10,
    margin: 20,
    fontSize: 20,
    color: COLOR.NOTE,
    width: '90%',
    marginBottom: 15,
    paddingTop: 10,
    borderWidth: 1,
    borderTopColor: COLOR.TOPLINE,
    borderColor: COLOR.BLUE,
  },
  textInput: {
    height: 150,
    justifyContent: 'flex-start',
    backgroundColor: COLOR.WHITE,
    borderRadius: 20,
    margin: 20,
    padding: 10,
    fontSize: 18,
    textAlignVertical: 'top',
    marginTop: 0,
  },
  selectedItem: {
    borderColor: COLOR.TAB_ICON,
    backgroundColor: COLOR.TAB_ICON,
    borderBottomColor: COLOR.BLUE,
  },
  allClearWrapper: {
    width: '45%',
    minHeight: 165,
    maxHeight: 165,
    borderRadius: 20,
    backgroundColor: COLOR.WHITE,
    margin: 5,
    marginTop: 5,
  },
  allClearText: {color: COLOR.PINK, margin: 10, fontSize: 18},
  contactTitle: {
    fontSize: 20,
    paddingBottom: 20,
    paddingTop: 5,
    borderBottomColor: COLOR.TOPLINE,
    borderBottomWidth: 1,
    marginTop: 25,
    borderTopColor: COLOR.TOPLINE,
    borderTopWidth: 1,
    color: COLOR.NAVBARBORDER,
  },
  buttonText: {color: COLOR.PINK, fontSize: 20},
  buttonStyle: {
    marginVertical: 5,
    paddingBottom: 10,
    borderBottomColor: COLOR.TOPLINE,
    borderBottomWidth: 1,
  },
  addHookups: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 40,
    marginTop: 10,
  },
  addHookupsImage: {width: 20, height: 20, marginRight: 10},
  addHookupText: {fontSize: 20, color: COLOR.WHITE},
});
