import {StyleSheet} from 'react-native';
import COLOR from '../../../constants/COLOR';

export default StyleSheet.create({
  contaier: {
    backgroundColor: COLOR.BLUE,
    width: '100%',
    height: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    marginLeft: 8,
    marginTop: 8,
  },
  main: {
    backgroundColor: COLOR.BLUE,
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
  },
  mainItem: {
    width: '45%',
    minHeight: 165,
    maxHeight: 165,

    borderRadius: 20,
    backgroundColor: COLOR.WHITE,
    margin: 5,
    marginTop: 5,
  },
  topItem: {
    height: '33%',
    justifyContent: 'center',
    width: '100%',
    alignItems: 'center',
    borderTopLeftRadius: 20,
    borderWidth: 1,
    borderTopRightRadius: 20,
    borderColor: COLOR.WHITE,
    borderBottomColor: COLOR.BLUE,
  },

  midelItem: {
    height: '33%',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  midelItemSelected: {
    height: '33%',
    backgroundColor: COLOR.PINK,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomItem: {
    height: '34%',
    justifyContent: 'center',
    width: '100%',
    alignItems: 'center',
    borderBottomLeftRadius: 20,
    borderWidth: 1,
    borderBottomRightRadius: 20,
    borderTopColor: COLOR.BLUE,
    borderColor: COLOR.WHITE,
  },
  bottomItemSelected: {
    height: '34%',
    justifyContent: 'center',
    width: '100%',
    alignItems: 'center',
    borderBottomLeftRadius: 20,
    borderWidth: 1,
    borderBottomRightRadius: 20,
    borderTopColor: COLOR.BLUE,
    borderColor: COLOR.PINK,
    backgroundColor: COLOR.PINK,
  },
  titleStyle: {margin: 10, fontSize: 18, opacity: 0.4},
  textColor: {color: COLOR.WHITE, fontSize: 18},
  textColorSelected: {color: COLOR.PINK, fontSize: 18},
  confirmButton: {position: 'absolute', bottom: -18, left: 140, zIndex: 2},
  confirmImage: {
    width: 50,
    height: 50,
  },
  resultTitle: {
    backgroundColor: COLOR.PINK,
    width: '100%',
    height: '100%',
    borderRadius: 20,
  },
  resultTitleText: {margin: 10, fontSize: 18, color: COLOR.WHITE},
  resultText: {
    margin: 5,
    marginHorizontal: 10,
    fontSize: 16,
    color: COLOR.WHITE,
  },
  mainNoteWrapper: {
    height: 300,
    width: '100%',
    backgroundColor: COLOR.BLUE,
  },
  noteWrapper: {
    width: '90%',
    margin: 20,
    marginBottom: 0,
    borderWidth: 1,
    borderTopColor: COLOR.TOPLINE,
    borderColor: COLOR.BLUE,
  },
  textNote: {
    marginTop: 10,
    margin: 20,
    fontSize: 20,
    color: COLOR.NOTE,
    width: '90%',
    marginBottom: 0,
    paddingTop: 10,
    borderWidth: 1,
    borderTopColor: COLOR.TOPLINE,
    borderColor: COLOR.BLUE,
  },
  textInput: {
    height: 150,
    justifyContent: 'flex-start',
    backgroundColor: COLOR.WHITE,
    borderRadius: 20,
    margin: 20,
    padding: 10,
    fontSize: 18,
    textAlignVertical: 'top',
    marginTop: 0,
  },
});
